// role_container.go - generated by api:generate role

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitEssayQuestionContainer() *handlers.EssayQuestionHandler {
	repo := sql.NewEssayQuestionRepository()
	service := services.NewEssayQuestionService(repo)
	return handlers.NewEssayQuestionHandler(service)
}
