// level_container.go - generated by api:generate level

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitLevelContainer() *handlers.LevelHandler {
	repo := sql.NewLevelRepository()
	service := services.NewLevelService(repo)
	return handlers.NewLevelHandler(service)
}
