// role_container.go - generated by api:generate role

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitMBadgeSettingsContainer() *handlers.MBadgeSettingsHandler {
	repo := sql.NewMBadgeSettingsRepository()
	service := services.NewMBadgeSettingsService(repo)
	return handlers.NewMBadgeSettingsHandler(service)
}
