// role_container.go - generated by api:generate role

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitMClassContainer() *handlers.MClassHandler {
	repo := sql.NewMClassRepository()
	service := services.NewMClassService(repo)
	return handlers.NewMClassHandler(service)
}
