// user_container.go - generated by api:generate user

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitMLessonContainer() *handlers.MLessonHandler {
	repo := sql.NewMLessonRepository()
	service := services.NewMLessonService(repo)
	return handlers.NewMLessonHandler(service)
}
