// user_container.go - generated by api:generate user

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitMMaterialContainer() *handlers.MMaterialHandler {
	repo := sql.NewMMaterialRepository()
	service := services.NewMMaterialService(repo)
	return handlers.NewMMaterialHandler(service)
}
