// user_container.go - generated by api:generate user

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitMSubLessonContainer() *handlers.MSubLessonHandler {
	repo := sql.NewMSubLessonRepository()
	service := services.NewMSubLessonService(repo)
	return handlers.NewMSubLessonHandler(service)
}
