// permission_container.go - generated by api:generate permission

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitPermissionContainer() *handlers.PermissionHandler {
	repo := sql.NewPermissionRepository()
	service := services.NewPermissionService(repo)
	return handlers.NewPermissionHandler(service)
}
