// position_container.go - generated by api:generate position

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitPositionContainer() *handlers.PositionHandler {
	repo := sql.NewPositionRepository()
	service := services.NewPositionService(repo)
	return handlers.NewPositionHandler(service)
}
