// role_container.go - generated by api:generate role

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitTCodeAnswerContainer() *handlers.TCodeAnswerHandler {
	repo := sql.NewTCodeAnswerRepository()
	service := services.NewTCodeAnswerService(repo)
	return handlers.NewTCodeAnswerHandler(service)
}
