// role_container.go - generated by api:generate role

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitTCodeQuestionContainer() *handlers.TCodeQuestionHandler {
	repo := sql.NewTCodeQuestionRepository()
	service := services.NewTCodeQuestionService(repo)
	return handlers.NewTCodeQuestionHandler(service)
}
