// role_container.go - generated by api:generate role

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitTStudentCourseContainer() *handlers.TStudentCourseHandler {
	repo := sql.NewTStudentCourseRepository()
	service := services.NewTStudentCourseService(repo)
	return handlers.NewTStudentCourseHandler(service)
}
