// title_container.go - generated by api:generate title

package container

import (
	"jk-api/api/http/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitTitleContainer() *handlers.TitleHandler {
	repo := sql.NewTitleRepository()
	service := services.NewTitleService(repo)
	return handlers.NewTitleHandler(service)
}
