// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateEssayQuestionDtoToModel(dto *dto.EssayQuestionCreateDto) (*models.EssayQuestion, error) {
	data := &models.EssayQuestion{
		CodeQuestionID: dto.CodeQuestionId,
		EssayQuestion:  dto.EssayQuestion,
		Answer:         dto.Answer,
		Answer1:        dto.Answer1,
		Answer2:        dto.Answer2,
		Answer3:        dto.Answer3,
		Answer4:        dto.Answer4,
	}

	return data, nil
}

func EssayQuestionModelToResponseDto(data *models.EssayQuestion) (*dto.EssayQuestionResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.EssayQuestionResponseDto{
		EssayQuestion: *data,
	}

	return responseDto, nil
}
