// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateMBadgeSettingsDtoToModel(dto *dto.CreateMBadgeSettingsDto) (*models.MBadgeSettings, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.MBadgeSettings{
		Name:     dto.Name,
		Image:    dto.Image,
		MinScore: dto.MinScore,
		MaxScore: dto.MaxScore,
	}

	return data, nil
}

func UpdateMBadgeSettingsDtoToModel(dto *dto.UpdateMBadgeSettingsDto) (
	payload map[string]interface{},
	associations map[string]interface{},
	err error,
) {
	payload = make(map[string]interface{})
	associations = make(map[string]interface{})

	if dto.Name != nil {
		payload["name"] = *dto.Name
	}

	if dto.Image != nil {
		payload["image"] = *dto.Image
	}

	if dto.MinScore != nil {
		payload["min_score"] = *dto.MinScore
	}

	if dto.MaxScore != nil {
		payload["max_score"] = *dto.MaxScore
	}
	if dto.IsActive != nil {
		payload["is_active"] = *dto.IsActive
	}

	return payload, associations, nil
}


func MBadgeSettingsModelToResponseDto(data *models.MBadgeSettings) (*dto.MBadgeSettingsResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.MBadgeSettingsResponseDto{
		MBadgeSettings: *data,
	}

	return responseDto, nil
}
