// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateMClassDtoToModel(dto *dto.CreateMClassDto) (*models.MClass, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.MClass{
		ClassName: dto.ClassName,
		SchoolName: dto.SchoolName,
		ClassCode: dto.ClassCode,
	}

	return data, nil
}

func UpdateMClassDtoToModel(dto *dto.UpdateMClassDto) (
	payload map[string]interface{},
	associations map[string]interface{},
	err error,
) {
	payload = make(map[string]interface{})
	associations = make(map[string]interface{})

	if dto.ClassName != nil {
		payload["class_name"] = *dto.ClassName
	}

	if dto.SchoolName != nil {
		payload["school_name"] = *dto.SchoolName
	}

	if dto.ClassCode != nil {
		payload["class_code"] = *dto.ClassCode
	}
	if dto.IsActive != nil {
		payload["is_active"] = *dto.IsActive
	}
	
	if dto.Teachers != nil {
		var users []models.User
		for _, id := range *dto.Teachers {
			users = append(users, models.User{ID: id})
		}
		associations["Teachers"] = users
	}

	if dto.Students != nil {
		var users []models.User
		for _, id := range *dto.Students {
			users = append(users, models.User{ID: id})
		}
		associations["Students"] = users
	}

	return payload, associations, nil
}


func MClassModelToResponseDto(data *models.MClass) (*dto.MClassResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.MClassResponseDto{
		MClass: *data,
	}

	return responseDto, nil
}
