// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateMCourseDtoToModel(dto *dto.CreateMCourseDto) (*models.MCourse, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.MCourse{
		CourseName:     dto.CourseName,
		Description: dto.Description,
		ImgThumbnail: dto.ImgThumbnail,
	}

	return data, nil
}

func UpdateMCourseDtoToModel(dto *dto.UpdateMCourseDto) (
	payload map[string]interface{},
	associations map[string]interface{},
	err error,
) {
	payload = make(map[string]interface{})
	associations = make(map[string]interface{})

	if dto.CourseName != nil {
		payload["course_name"] = *dto.CourseName
	}

	if dto.ImgThumbnail != nil {
		payload["img_thumbnail"] = *dto.ImgThumbnail
	}

	if dto.Description != nil {
		payload["description"] = *dto.Description
	}

	if dto.Published != nil {
		payload["published"] = *dto.Published
	}
	if dto.IsActive != nil {
		payload["is_active"] = *dto.IsActive
	}

	return payload, associations, nil
}


func MCourseModelToResponseDto(data *models.MCourse) (*dto.MCourseResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.MCourseResponseDto{
		MCourse: *data,
	}

	return responseDto, nil
}
