// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateMLevelDtoToModel(dto *dto.CreateMLevelDto) (*models.MLevel, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.MLevel{
		
	}

	return data, nil
}

func UpdateMLevelDtoToModel(dto *dto.UpdateMLevelDto) (
	payload map[string]interface{},
	associations map[string]interface{},
	err error,
) {
	payload = make(map[string]interface{})
	associations = make(map[string]interface{})

	if dto.LevelName != nil {
		payload["level_name"] = *dto.LevelName
	}

	if dto.Description != nil {
		payload["description"] = *dto.Description
	}

	if dto.IsActive != nil {
		payload["is_active"] = *dto.IsActive
	}

	return payload, associations, nil
}


func MLevelModelToResponseDto(data *models.MLevel) (*dto.MLevelResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.MLevelResponseDto{
		MLevel: *data,
	}

	return responseDto, nil
}
