// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateTCodeQuestionDtoToModel(dto *dto.TCodeQuestionCreateDto) (*models.TCodeQuestion, error) {
	data := &models.TCodeQuestion{
		SubLessonID:  dto.SubLessonID,
		CodeQuestion: dto.CodeQuestion,
		Image:          dto.Image,
		Score:          dto.Score,
		Hint:           dto.Hint,
	}

	return data, nil
}

func TCodeQuestionModelToResponseDto(data *models.TCodeQuestion) (*dto.TCodeQuestionResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.TCodeQuestionResponseDto{
		TCodeQuestion: *data,
	}

	return responseDto, nil
}
