// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateTCodeAnswerDtoToModel(dto *dto.TCodeAnswerCreateDto, userID int64) (*models.TCodeAnswer, error) {
	data := &models.TCodeAnswer{
		UserID:         userID,
		CodeQuestionID: dto.CodeQuestionID,
		IsCodeRight:    dto.IsCodeRight,
		ExploringScore: dto.ExploringScore,
	}

	return data, nil
}

func TCodeAnswerModelToResponseDto(data *models.TCodeAnswer) (*dto.TCodeAnswerResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.TCodeAnswerResponseDto{
		TCodeAnswer: *data,
	}

	return responseDto, nil
}
