// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CompleteTStudentProgressDtoToModel(dto *dto.CompleteTStudentProgressDto, userID int64) (*models.TStudentProgress, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.TStudentProgress{
		UserID: userID,
		SubLessonID: dto.SubLessonID,
		Status: dto.Status,
	}

	return data, nil
}

func TStudentProgressModelToResponseDto(data *models.TStudentProgress) (*dto.TStudentProgressResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.TStudentProgressResponseDto{
		TStudentProgress: *data,
	}

	return responseDto, nil
}
