// role_mapper.go - generated by api:generate role

package mapper

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func EnrollTStudentCourseDtoToModel(userID int64, courseID int64) (*models.TStudentCourse, error) {
	data := &models.TStudentCourse{
		UserID: userID,
		CourseID: courseID,
		BadgeID: 1,
		ProgressPercentage: 0,
		TotalScore: 0,
	}

	return data, nil
}

func TStudentCourseModelToResponseDto(data *models.TStudentCourse) (*dto.TStudentCourseResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.TStudentCourseResponseDto{
		TStudentCourse: *data,
	}

	return responseDto, nil
}
