// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/pkg/services/v1"
)

type EssayQuestionHandler struct {
	Service services.EssayQuestionService
}

func NewEssayQuestionHandler(service services.EssayQuestionService) *EssayQuestionHandler {
	return &EssayQuestionHandler{Service: service}
}

func (h *EssayQuestionHandler) CreateEssayQuestionHandler(input *dto.EssayQuestionCreateDto) (*dto.EssayQuestionResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	EssayQuestionService := h.Service.WithTx(db)

	payload, err := mapper.CreateEssayQuestionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := EssayQuestionService.CreateEssayQuestion(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.EssayQuestionModelToResponseDto(createdData)
}

func (h *EssayQuestionHandler) GetEssayQuestionsByCodeQuestionIDHandler(filter dto.EssayQuestionFilterDto, subLessonID int64) ([]dto.EssayQuestionResponseDto, error) {
	data, err := h.Service.GetEssayQuestionsByCodeQuestionID(subLessonID)
	if err != nil {
		return nil, err
	}
	var response []dto.EssayQuestionResponseDto
	for _, item := range data {
		mappedItem, err := mapper.EssayQuestionModelToResponseDto(&item)
		if err != nil {
			return nil, err
		}
		response = append(response, *mappedItem)
	}
	return response, nil
}

func (h *EssayQuestionHandler) GetEssayQuestionHandlerByID(filter dto.EssayQuestionFilterDto, id int64) (*dto.EssayQuestionResponseDto, error) {
	data, err := h.Service.GetEssayQuestionByID(id)
	if err != nil {
		return nil, err
	}
	return mapper.EssayQuestionModelToResponseDto(data)
}
