// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/pkg/services/v1"
)

type MBadgeSettingsHandler struct {
	Service services.MBadgeSettingsService
}

func NewMBadgeSettingsHandler(service services.MBadgeSettingsService) *MBadgeSettingsHandler {
	return &MBadgeSettingsHandler{Service: service}
}

func (h *MBadgeSettingsHandler) CreateMBadgeSettingsHandler(input *dto.CreateMBadgeSettingsDto) (*dto.MBadgeSettingsResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	MBadgeSettingsService := h.Service.WithTx(db)

	payload, err := mapper.CreateMBadgeSettingsDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := MBadgeSettingsService.CreateMBadgeSettings(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.MBadgeSettingsModelToResponseDto(createdData)
}

func (h *MBadgeSettingsHandler) UpdateMBadgeSettingsHandler(id int64, input *dto.UpdateMBadgeSettingsDto) (*models.MBadgeSettings, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	MBadgeSettingsService := h.Service.WithTx(db)

	payload, associations, err := mapper.UpdateMBadgeSettingsDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := MBadgeSettingsService.UpdateMBadgeSettings(id, payload, associations)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *MBadgeSettingsHandler) DeleteMBadgeSettingsHandler(id int64) error {
	return h.Service.DeleteMBadgeSettings(id)
}

func (h *MBadgeSettingsHandler) GetMBadgeSettingsByIDHandler(id int64, filter dto.MBadgeSettingsFilterDto) (*models.MBadgeSettings, error) {
	return h.Service.GetMBadgeSettingsByID(id, filter)
}

func (h *MBadgeSettingsHandler) GetAllMBadgeSettingsHandler(filter dto.MBadgeSettingsFilterDto) ([]models.MBadgeSettings, error) {
	return h.Service.GetAllMBadgeSettings(filter)
}
