// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/pkg/services/v1"
)

type MClassHandler struct {
	Service services.MClassService
}

func NewMClassHandler(service services.MClassService) *MClassHandler {
	return &MClassHandler{Service: service}
}

func (h *MClassHandler) CreateMClassHandler(input *dto.CreateMClassDto) (*dto.MClassResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	MClassService := h.Service.WithTx(db)

	payload, err := mapper.CreateMClassDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := MClassService.CreateMClass(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.MClassModelToResponseDto(createdData)
}

func (h *MClassHandler) UpdateMClassHandler(id int64, input *dto.UpdateMClassDto) (*models.MClass, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	MClassService := h.Service.WithTx(db)

	payload, associations, err := mapper.UpdateMClassDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := MClassService.UpdateMClass(id, payload, associations)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *MClassHandler) DeleteMClassHandler(id int64) error {
	return h.Service.DeleteMClass(id)
}

func (h *MClassHandler) GetMClassByIDHandler(id int64, filter dto.MClassFilterDto) (*models.MClass, error) {
	return h.Service.GetMClassByID(id, filter)
}

func (h *MClassHandler) GetAllMClassesHandler(filter dto.MClassFilterDto) ([]models.MClass, error) {
	return h.Service.GetAllMClasses(filter)
}
