// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/pkg/services/v1"
)

type MCourseHandler struct {
	Service services.MCourseService
}

func NewMCourseHandler(service services.MCourseService) *MCourseHandler {
	return &MCourseHandler{Service: service}
}

func (h *MCourseHandler) CreateMCourseHandler(input *dto.CreateMCourseDto) (*dto.MCourseResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	MCourseService := h.Service.WithTx(db)

	payload, err := mapper.CreateMCourseDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := MCourseService.CreateMCourse(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.MCourseModelToResponseDto(createdData)
}

func (h *MCourseHandler) UpdateMCourseHandler(id int64, input *dto.UpdateMCourseDto) (*models.MCourse, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	MCourseService := h.Service.WithTx(db)

	payload, associations, err := mapper.UpdateMCourseDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := MCourseService.UpdateMCourse(id, payload, associations)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *MCourseHandler) DeleteMCourseHandler(id int64) error {
	return h.Service.DeleteMCourse(id)
}

func (h *MCourseHandler) GetMCourseByIDHandler(id int64, filter dto.MCourseFilterDto) (*models.MCourse, error) {
	return h.Service.GetMCourseByID(id, filter)
}

func (h *MCourseHandler) GetAllMCoursesHandler(filter dto.MCourseFilterDto) ([]models.MCourse, error) {
	return h.Service.GetAllMCourses(filter)
}
