// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/internal/database/models"
	"jk-api/pkg/services/v1"
)

type MLevelHandler struct {
	Service services.MLevelService
}

func NewMLevelHandler(service services.MLevelService) *MLevelHandler {
	return &MLevelHandler{Service: service}
}

func (h *MLevelHandler) CreateMLevelHandler(input *dto.CreateMLevelDto) (*dto.MLevelResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	MLevelService := h.Service.WithTx(db)

	payload, err := mapper.CreateMLevelDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := MLevelService.CreateMLevel(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.MLevelModelToResponseDto(createdData)
}

func (h *MLevelHandler) UpdateMLevelHandler(id int64, input *dto.UpdateMLevelDto) (*models.MLevel, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r)
		}
		if !committed {
			db.Rollback()
		}
	}()

	MLevelService := h.Service.WithTx(db)

	payload, associations, err := mapper.UpdateMLevelDtoToModel(input)
	if err != nil {
		return nil, err
	}

	updatedData, err := MLevelService.UpdateMLevel(id, payload, associations)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return updatedData, nil
}

func (h *MLevelHandler) DeleteMLevelHandler(id int64) error {
	return h.Service.DeleteMLevel(id)
}

func (h *MLevelHandler) GetMLevelByIDHandler(id int64, filter dto.MLevelFilterDto) (*models.MLevel, error) {
	return h.Service.GetMLevelByID(id, filter)
}

func (h *MLevelHandler) GetAllMLevelsHandler(filter dto.MLevelFilterDto) ([]models.MLevel, error) {
	return h.Service.GetAllMLevels(filter)
}
