// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/pkg/services/v1"
)

type TCodeQuestionHandler struct {
	Service services.TCodeQuestionService
}

func NewTCodeQuestionHandler(service services.TCodeQuestionService) *TCodeQuestionHandler {
	return &TCodeQuestionHandler{Service: service}
}

func (h *TCodeQuestionHandler) CreateTCodeQuestionHandler(input *dto.TCodeQuestionCreateDto) (*dto.TCodeQuestionResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	TCodeQuestionService := h.Service.WithTx(db)

	payload, err := mapper.CreateTCodeQuestionDtoToModel(input)
	if err != nil {
		return nil, err
	}

	createdData, err := TCodeQuestionService.CreateCodeQuestion(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.TCodeQuestionModelToResponseDto(createdData)
}

func (h *TCodeQuestionHandler) GetTCodeQuestionsBySubLessonIDHandler(filter dto.TCodeQuestionFilterDto, subLessonID int64) ([]dto.TCodeQuestionResponseDto, error) {
	data, err := h.Service.GetCodeQuestionsBySubLessonID(subLessonID)
	if err != nil {
		return nil, err
	}
	var response []dto.TCodeQuestionResponseDto
	for _, item := range data {
		mappedItem, err := mapper.TCodeQuestionModelToResponseDto(&item)
		if err != nil {
			return nil, err
		}
		response = append(response, *mappedItem)
	}
	return response, nil
}

func (h *TCodeQuestionHandler) GetTCodeQuestionHandlerByID(filter dto.TCodeQuestionFilterDto, id int64) (*dto.TCodeQuestionResponseDto, error) {
	data, err := h.Service.GetCodeQuestionByID(id)
	if err != nil {
		return nil, err
	}
	return mapper.TCodeQuestionModelToResponseDto(data)
}
