// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/pkg/services/v1"
)

type TCodeAnswerHandler struct {
	Service services.TCodeAnswerService
}

func NewTCodeAnswerHandler(service services.TCodeAnswerService) *TCodeAnswerHandler {
	return &TCodeAnswerHandler{Service: service}
}

func (h *TCodeAnswerHandler) CreateTCodeAnswerHandler(input *dto.TCodeAnswerCreateDto, userID int64) (*dto.TCodeAnswerResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	TCodeAnswerService := h.Service.WithTx(db)

	payload, err := mapper.CreateTCodeAnswerDtoToModel(input, userID)
	if err != nil {
		return nil, err
	}

	createdData, err := TCodeAnswerService.CreateTCodeAnswer(payload, userID)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.TCodeAnswerModelToResponseDto(createdData)
}

func (h *TCodeAnswerHandler) GetTCodeAnswersByCodeQuestionIDHandler(filter dto.TCodeAnswerFilterDto, codeQuestionID int64) ([]dto.TCodeAnswerResponseDto, error) {
	data, err := h.Service.GetTCodeAnswersByCodeQuestionID(codeQuestionID)
	if err != nil {
		return nil, err
	}
	var response []dto.TCodeAnswerResponseDto
	for _, item := range data {
		mappedItem, err := mapper.TCodeAnswerModelToResponseDto(&item)
		if err != nil {
			return nil, err
		}
		response = append(response, *mappedItem)
	}
	return response, nil
}


