// role_handler.go - generated by api:generate role

package handlers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/controllers/v1/mapper"
	"jk-api/pkg/services/v1"
)

type TStudentCourseHandler struct {
	Service services.TStudentCourseService
}

func NewTStudentCourseHandler(service services.TStudentCourseService) *TStudentCourseHandler {
	return &TStudentCourseHandler{Service: service}
}

func (h *TStudentCourseHandler) EnrollTStudentCourseHandler(userID int64, courseID int64) (*dto.TStudentCourseResponseDto, error) {
	db := h.Service.GetDB().Begin()
	committed := false
	defer func() {
		if r := recover(); r != nil {
			db.Rollback()
			panic(r) // terusin panic biar gak ketelen
		}
		if !committed {
			db.Rollback()
		}
	}()

	TStudentCourseService := h.Service.WithTx(db)

	payload, err := mapper.EnrollTStudentCourseDtoToModel(userID, courseID)
	if err != nil {
		return nil, err
	}

	createdData, err := TStudentCourseService.EnrollTStudentCourse(payload)
	if err != nil {
		return nil, err
	}

	if err := db.Commit().Error; err != nil {
		return nil, err
	}
	committed = true

	return mapper.TStudentCourseModelToResponseDto(createdData)
}

func (h *TStudentCourseHandler) GetTStudentCourseByIDHandler(filter dto.TStudentCourseFilterDto, userID int64, id int64) (*dto.TStudentCourseResponseDto, error) {
	data, err := h.Service.GetTStudentCourseByID(id, filter, userID)
	if err != nil {
		return nil, err
	}
	return mapper.TStudentCourseModelToResponseDto(data)
}

func (h *TStudentCourseHandler) GetMyCoursesHandler(UserID int64,filter dto.TStudentCourseFilterDto,) ([]dto.TStudentCourseResponseDto, error) {

	data, err := h.Service.GetMyCourse(UserID, filter)
	if err != nil {
		return nil, err
	}

	// 🔥 handle empty biar ga null
	if len(data) == 0 {
		return []dto.TStudentCourseResponseDto{}, nil
	}

	response := make([]dto.TStudentCourseResponseDto, 0, len(data))

	for _, item := range data {
		dtoItem, err := mapper.TStudentCourseModelToResponseDto(&item)
		if err != nil {
			return nil, err
		}
		response = append(response, *dtoItem)
	}

	return response, nil
}
