// user_controller.go - generated by api:generate user

package controllers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/helper"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func GetMLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		cursor, _ := helper.ParseQueryInt64(c, "cursor")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name")
		sort := c.Query("sort", "id")
		order := c.Query("order", "asc")
		deleted := c.Query("show_deleted", "false") == "true"

		filter := dto.MLessonFilterDto{
			Preload:     c.Query("preload", "false") == "true",
			Cursor:      cursor,
			Limit:       limit,
			Name:        name,
			Sort:        sort,
			Order:       order,
			ShowDeleted: deleted,
		}

		data, total, err := cn.MLessonHandler.GetAllMLessonsHandler(filter)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data, total)
	}
}

func GetMLessonByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.MLessonFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.MLessonHandler.GetMLessonByIDHandler(id, filter)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}

func CreateMLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateMLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.MLessonHandler.CreateMLessonHandler(&input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, result)
	}
}

func UpdateMLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateMLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.MLessonHandler.UpdateMLessonHandler(id, &input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, updated)
	}
}

func DeleteMLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.MLessonHandler.DeleteMLessonHandler(id); err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponseWithMessage(c, "Lesson deleted successfully", nil)
	}
}

func BulkCreateMLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkCreateMLessonsDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk create")
		}
		if len(input.Data) == 0 {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "No data provided")
		}
		
		createdMLessons, err := cn.MLessonHandler.BulkCreateMLessonsHandler(&input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, createdMLessons)
	}
}

func BulkUpdateMLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkUpdateMLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk update")
		}

		// Use the handler's bulk update which performs UpdateMany in one query
		updatedUsers, err := cn.MLessonHandler.BulkUpdateMLessonsHandler(&input)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusInternalServerError, fmt.Sprintf("Failed to bulk update users: %v", err))
		}

		return presenters.SuccessResponse(c, updatedUsers)
	}
}

func BulkDeleteMLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkDeleteMLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk delete")
		}

		if len(input.IDs) == 0 {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "No Division IDs provided")
		}

		err := cn.MLessonHandler.BulkDeleteMLessonsHandler(&input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SuccessResponseWithMessage(c, fmt.Sprintf("Successfully deleted %d Lessons", len(input.IDs)), nil)
	}
}
