// user_controller.go - generated by api:generate user

package controllers

import (
	"fmt"
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"jk-api/internal/helper"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func GetMSubLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		cursor, _ := helper.ParseQueryInt64(c, "cursor")
		limit, _ := helper.ParseQueryInt64(c, "limit")
		name := c.Query("name")
		sort := c.Query("sort", "id")
		order := c.Query("order", "asc")
		deleted := c.Query("show_deleted", "false") == "true"

		filter := dto.MSubLessonFilterDto{
			Preload:     c.Query("preload", "false") == "true",
			Cursor:      cursor,
			Limit:       limit,
			Name:        name,
			Sort:        sort,
			Order:       order,
			ShowDeleted: deleted,
		}

		data, total, err := cn.MSubLessonHandler.GetAllMSubLessonsHandler(filter)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data, total)
	}
}

func GetMSubLessonByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		filter := dto.MSubLessonFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		data, err := cn.MSubLessonHandler.GetMSubLessonByIDHandler(id, filter)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}

func CreateMSubLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.CreateMSubLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.MSubLessonHandler.CreateMSubLessonHandler(&input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, result)
	}
}

func UpdateMSubLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		var input dto.UpdateMSubLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid input")
		}

		updated, err := cn.MSubLessonHandler.UpdateMSubLessonHandler(id, &input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, updated)
	}
}

func DeleteMSubLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid ID")
		}

		if err := cn.MSubLessonHandler.DeleteMSubLessonHandler(id); err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponseWithMessage(c, "SubLesson deleted successfully", nil)
	}
}

func BulkCreateMSubLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkCreateMSubLessonsDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk create")
		}
		if len(input.Data) == 0 {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "No data provided")
		}
		
		createdMSubLessons, err := cn.MSubLessonHandler.BulkCreateMSubLessonsHandler(&input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, createdMSubLessons)
	}
}

func BulkUpdateMSubLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkUpdateMSubLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk update")
		}

		// Use the handler's bulk update which performs UpdateMany in one query
		updatedUsers, err := cn.MSubLessonHandler.BulkUpdateMSubLessonsHandler(&input)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusInternalServerError, fmt.Sprintf("Failed to bulk update users: %v", err))
		}

		return presenters.SuccessResponse(c, updatedUsers)
	}
}

func BulkDeleteMSubLessons(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.BulkDeleteMSubLessonDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request body for bulk delete")
		}

		if len(input.IDs) == 0 {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "No Division IDs provided")
		}

		err := cn.MSubLessonHandler.BulkDeleteMSubLessonsHandler(&input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}

		return presenters.SuccessResponseWithMessage(c, fmt.Sprintf("Successfully deleted %d SubLessons", len(input.IDs)), nil)
	}
}
