// role_controller.go - generated by api:generate role

package controllers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func CreateTCodeAnswer(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		userID := c.Locals("user_id").(int64)
		var input dto.TCodeAnswerCreateDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.TCodeAnswerHandler.CreateTCodeAnswerHandler(&input, userID)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, result)
	}
}

func GetTCodeAnswersByCodeQuestionID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		codeQuestionID, err := strconv.ParseInt(c.Params("codeQuestionID"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid code question ID")
		}
	
		filter := dto.TCodeAnswerFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.TCodeAnswerHandler.GetTCodeAnswersByCodeQuestionIDHandler(filter, codeQuestionID)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}


