// role_controller.go - generated by api:generate role

package controllers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func CreateTCodeQuestions(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var input dto.TCodeQuestionCreateDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.TCodeQuestionHandler.CreateTCodeQuestionHandler(&input)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, result)
	}
}

func GetTcodeQuestionsBySubLessonID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		subLessonID, err := strconv.ParseInt(c.Params("subLessonID"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid sub lesson ID")
		}
	
		filter := dto.TCodeQuestionFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.TCodeQuestionHandler.GetTCodeQuestionsBySubLessonIDHandler(filter, subLessonID)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}

func GetTCodeQuestionByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid course ID")
		}

		filter := dto.TCodeQuestionFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.TCodeQuestionHandler.GetTCodeQuestionHandlerByID(filter, id)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}

