// role_controller.go - generated by api:generate role

package controllers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func CreateTEssayAnswer(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		userID := c.Locals("user_id").(int64)
		var input dto.TEssayAnswerCreateDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid request")
		}

		result, err := cn.TEssayAnswerHandler.CreateTEssayAnswerHandler(&input, userID)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, result)
	}
}

func GetTEssayAnswersByEssayQuestionIDAndUserID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		essayQuestionID, err := strconv.ParseInt(c.Params("essayQuestionID"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid essay question ID")
		}
		userID := c.Locals("user_id").(int64)
		filter := dto.TEssayAnswerFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.TEssayAnswerHandler.GetTEssayAnswersByEssayQuestionIDAndUserIDHandler(filter, essayQuestionID, userID)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}


