// role_controller.go - generated by api:generate role

package controllers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func GetMyCourse(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		userID := c.Locals("user_id").(int64)
		filter := dto.TStudentCourseFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.TStudentCourseHandler.GetMyCoursesHandler(userID, filter)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}

func GetTStudentCourseByID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		userID := c.Locals("user_id").(int64)
		id, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid course ID")
		}

		filter := dto.TStudentCourseFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.TStudentCourseHandler.GetTStudentCourseByIDHandler(filter, userID, id)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}

func EnrollCourse(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		userID := c.Locals("user_id").(int64)

		courseID, err := strconv.ParseInt(c.Params("id"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(
				c,
				fiber.StatusBadRequest,
				"Invalid course id",
			)
		}

		result, err := cn.TStudentCourseHandler.
			EnrollTStudentCourseHandler(userID, courseID)

		if err != nil {
			return presenters.ErrorResponse(
				c,
				fiber.StatusInternalServerError,
				err,
			)
		}

		return presenters.SuccessResponse(c, result)
	}
}
