// role_controller.go - generated by api:generate role

package controllers

import (
	"jk-api/api/http/controllers/v1/dto"
	"jk-api/api/http/presenters"
	"jk-api/internal/container"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func CreateTWonderingScore(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		userID := c.Locals("user_id").(int64)
		
		var input dto.TWonderingScoreCreateDto
		if err := c.BodyParser(&input); err != nil {
			return presenters.ErrorResponseWithMessage(
				c,
				fiber.StatusBadRequest,
				"Invalid request body",
			)
		}

		result, err := cn.TWonderingScoreHandler.CreateTWonderingScoreHandler(
			&input,
			userID,
		)

		if err != nil {
			return presenters.ErrorResponse(
				c,
				fiber.StatusInternalServerError,
				err,
			)
		}

		return presenters.SuccessResponse(c, result)
	}
}

func GetTWonderingScoresBySubLessonID(cn *container.AppContainer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		userID := c.Locals("user_id").(int64)

		subLessonID, err := strconv.ParseInt(c.Params("subLessonID"), 10, 64)
		if err != nil {
			return presenters.ErrorResponseWithMessage(c, fiber.StatusBadRequest, "Invalid sub lesson ID")
		}

		filter := dto.TWonderingScoreFilterDto{
			Preload: c.Query("preload", "false") == "true",
		}

		data, err := cn.TWonderingScoreHandler.GetTWonderingScoresBySubLessonIDAndUserIDHandler(filter, subLessonID, userID)
		if err != nil {
			return presenters.ErrorResponse(c, fiber.StatusInternalServerError, err)
		}
		return presenters.SuccessResponse(c, data)
	}
}
