// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func MBadgeSettings(router fiber.Router, c *container.AppContainer) {
	app := router.Group("m_badge_settings", middleware.JWTMiddleware())
	app.Get("/", controllers.GetMBadgeSettings(c))
	app.Post("/", controllers.CreateMBadgeSettings(c))
	app.Get("/:id", controllers.GetMBadgeSettingsByID(c))
	app.Put("/:id", controllers.UpdateMBadgeSettings(c))
	app.Delete("/:id", controllers.DeleteMBadgeSettings(c))
}
