// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func MClassRoute(router fiber.Router, c *container.AppContainer) {
	app := router.Group("m_classes", middleware.JWTMiddleware())
	app.Get("/", controllers.GetMClasses(c))
	app.Post("/", controllers.CreateMClasses(c))
	app.Get("/:id", controllers.GetMClassByID(c))
	app.Put("/:id", controllers.UpdateMClasses(c))
	app.Delete("/:id", controllers.DeleteMClasses(c))
}
