// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func MCourses(router fiber.Router, c *container.AppContainer) {
	app := router.Group("m_courses", middleware.JWTMiddleware())
	app.Get("/", controllers.GetMCourses(c))
	app.Post("/", controllers.CreateMCourse(c))
	app.Get("/:id", controllers.GetMCourseByID(c))
	app.Put("/:id", controllers.UpdateMCourse(c))
	app.Delete("/:id", controllers.DeleteMCourse(c))
}
