// user_routes.go - generated by api:generate user

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func MLessonRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("m_lessons", middleware.JWTMiddleware())

	app.Get("/", controllers.GetMLessons(c))
	app.Get("/:id", controllers.GetMLessonByID(c))
	app.Post("/bulk-create", controllers.BulkCreateMLessons(c))
	app.Put("/bulk-update", controllers.BulkUpdateMLessons(c))
	app.Delete("/bulk-delete", controllers.BulkDeleteMLessons(c))
	app.Post("/", controllers.CreateMLessons(c))
	app.Put("/:id", controllers.UpdateMLessons(c))
	app.Delete("/:id", controllers.DeleteMLessons(c))
}
