// level_routes.go - generated by api:generate level

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func MLevelRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("/m_levels", middleware.JWTMiddleware())
	app.Get("/", controllers.GetMLevels(c))
	app.Post("/", controllers.CreateMLevels(c))
	app.Get("/:id", controllers.GetMLevelByID(c))
	app.Put("/:id", controllers.UpdateMLevels(c))
	app.Delete("/:id", controllers.DeleteMLevels(c))
}
