// user_routes.go - generated by api:generate user

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func MSubLessonRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("m_sub_lessons", middleware.JWTMiddleware())

	app.Get("/", controllers.GetMSubLessons(c))
	app.Get("/:id", controllers.GetMSubLessonByID(c))
	app.Post("/bulk-create", controllers.BulkCreateMSubLessons(c))
	app.Put("/bulk-update", controllers.BulkUpdateMSubLessons(c))
	app.Delete("/bulk-delete", controllers.BulkDeleteMSubLessons(c))
	app.Post("/", controllers.CreateMSubLessons(c))
	app.Put("/:id", controllers.UpdateMSubLessons(c))
	app.Delete("/:id", controllers.DeleteMSubLessons(c))
}
