// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func TCodeQuestionRoute(router fiber.Router, c *container.AppContainer) {
	app := router.Group("code_questions", middleware.JWTMiddleware())
	app.Get("/sub_lesson/:subLessonID", controllers.GetTcodeQuestionsBySubLessonID(c))
	app.Get("/:id", controllers.GetTCodeQuestionByID(c))
	app.Post("/", controllers.CreateTCodeQuestions(c))
	
}
