// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func TCodeAnswerRoute(router fiber.Router, c *container.AppContainer) {
	app := router.Group("t_code_answer", middleware.JWTMiddleware())
	app.Get("/code_questions/:codeQuestionID", controllers.GetTCodeAnswersByCodeQuestionID(c))
	app.Post("/", controllers.CreateTCodeAnswer(c))
	
}
