// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func EssayQuestionRoute(router fiber.Router, c *container.AppContainer) {
	app := router.Group("essay_questions", middleware.JWTMiddleware())
	app.Get("/code_questions/:codeQuestionID", controllers.GetEssayQuestionsByCodeQuestionID(c))
	app.Get("/:id", controllers.GetEssayQuestionByID(c))
	app.Post("/", controllers.CreateEssayQuestions(c))
	
}
