// role_routes.go - generated by api:generate role

package routes

import (
	"jk-api/api/http/controllers/v1"
	"jk-api/api/http/middleware"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func TStudentProgressRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("t_student_progress", middleware.JWTMiddleware())
	app.Post("/complete", controllers.CompleteTStudentProgress(c))
}
