// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

type EssayQuestionCreateDto struct {
	CodeQuestionId int64  `json:"code_question_id" validate:"required"`
	EssayQuestion string `json:"essay_question" validate:"required"`
	Answer		string `json:"answer" validate:"required"`
	Answer1	string `json:"answer_1"`
	Answer2	string `json:"answer_2"`
	Answer3	string `json:"answer_3"`
	Answer4	string `json:"answer_4"`
}

// EssayQuestionResponseDto represents a detailed view of EssayQuestion with related data.
type EssayQuestionResponseDto struct {
	models.EssayQuestion
}

type EssayQuestionFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
