// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

// CreateTitleDto is used when creating a new Title.
type CreateMBadgeSettingsDto struct {
	Name	   string    `json:"name"`
	Image      string    `json:"image"`
	MinScore   int       `json:"min_score"`
	MaxScore   int       `json:"max_score"`
}

// UpdateMBadgeSettingsDto is used when updating an existing MBadgeSettings.
type UpdateMBadgeSettingsDto struct {
	Name	   *string   `json:"name"`
	Image      *string   `json:"image"`
	MinScore   *int      `json:"min_score"`
	MaxScore   *int      `json:"max_score"`
	IsActive   *bool     `json:"is_active"`
}

// MBadgeSettingsResponseDto represents a detailed view of MBadgeSettings with related data.
type MBadgeSettingsResponseDto struct {
	models.MBadgeSettings
}

type MBadgeSettingsFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
