// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

// CreateTitleDto is used when creating a new Title.
type CreateMClassDto struct {
	ClassName string `json:"class_name"`
	SchoolName string `json:"school_name"`
	ClassCode string `json:"class_code"`
}

// UpdateMClassDto is used when updating an existing MClass.
type UpdateMClassDto struct {
	ClassName  *string    `json:"class_name"`
	SchoolName *string    `json:"school_name"`
	ClassCode  *string    `json:"class_code"`
	IsActive   *bool      `json:"is_active"`
	DeletedAt  *time.Time `json:"deleted_at"`
	Teachers   *[]int64   `json:"teachers"`
	Students   *[]int64   `json:"students"`
}

type BulkCreateMClassDto struct {
	Data []*CreateMClassDto `json:"data" binding:"required"`
}

type BulkUpdateMClassDto struct {
	IDs  []int64         `json:"ids" binding:"required"`
	Data *UpdateMClassDto `json:"data" binding:"required"`
}

type BulkDeleteMClassDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}

// MClassResponseDto represents a detailed view of MClass with related data.
type MClassResponseDto struct {
	models.MClass
}

type MClassFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
