// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

// CreateMCourseDto is used when creating a new MCourse.
type CreateMCourseDto struct {
     CourseName string `json:"course_name" binding:"required"`
	 Description string `json:"description"`
	 ImgThumbnail string `json:"img_thumbnail"`
}

// UpdateMCourseDto is used when updating an existing MCourse.
type UpdateMCourseDto struct {
	CourseName *string `json:"course_name"`
	Description *string `json:"description"`
	ImgThumbnail *string `json:"img_thumbnail"`
	Published *bool `json:"published"`
	IsActive *bool `json:"isactive"`
}

// MCourseResponseDto represents a detailed view of MCourse with related data.
type MCourseResponseDto struct {
	models.MCourse
}

type MCourseFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
