// level_dto.go - generated by api:generate level

package dto

import (
	"jk-api/internal/database/models"
)

type CreateMLevelDto struct {
	LevelName string `json:"level_name" binding:"required"`
	Description string `json:"description"`
}

type UpdateMLevelDto struct {
	LevelName *string `json:"level_name"`
	Description *string `json:"description"`
	IsActive *bool `json:"is_active"`
}

type MLevelFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}

type MLevelResponseDto struct {
	models.MLevel
}
