// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

// CreateMLesson is used when creating a new MLesson.
type CreateMLessonDto struct {
	CourseID int64 `json:"course_id"`
	LevelID int64 `json:"level_id"`
    Title string `json:"title"`
	Description string `json:"description"`
	Position int `json:"position"`
	ImgThumbnail string `json:"img_thumbnail"`
}

// UpdateMLesson is used when updating an existing MLesson.
type UpdateMLessonDto struct {
	CourseID *int64 `json:"course_id"`
	LevelID *int64 `json:"level_id"`
    Title *string `json:"title"`
	Description *string `json:"description"`
	Position *int `json:"position"`
	ImgThumbnail *string `json:"img_thumbnail"`
	Published *bool `json:"published"`
	IsActive *bool `json:"isactive"`
}

type BulkCreateMLessonsDto struct {
	Data []*CreateMLessonDto `json:"data" binding:"required"`
}

type BulkUpdateMLessonDto struct {
	IDs  []int64              `json:"ids" binding:"required"`
	Data *UpdateMLessonDto `json:"data" binding:"required"`
}

type BulkDeleteMLessonDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}

// MLessonResponseDto represents a detailed view of MLesson with related data.
type MLessonResponseDto struct {
	models.MLesson
}

type MLessonFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
