// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

// CreateMMaterial is used when creating a new MMaterial.
type CreateMMaterialDto struct {
	SubLessonID int64  `json:"sub_lesson_id" binding:"required"`
	Title       string `json:"title" binding:"required"`
	Materials  string `json:"materials" binding:"required"`
	URLVideo  string `json:"url_video"`
	ContentPosition int    `json:"content_position" binding:"required"`
	PromptLLM       string `json:"prompt_llm" binding:"required"`
}

// UpdateMMaterial is used when updating an existing MMaterial.
type UpdateMMaterialDto struct {
	SubLessonID *int64  `json:"sub_lesson_id,omitempty"`
	Title       *string `json:"title,omitempty"`
	Materials  *string `json:"materials,omitempty"`
	URLVideo  *string `json:"url_video,omitempty"`
	ContentPosition *int    `json:"content_position,omitempty"`
	PromptLLM       *string `json:"prompt_llm,omitempty"`
	Published       *bool   `json:"published,omitempty"`
	IsActive        *bool   `json:"isactive,omitempty"`
}

type BulkCreateMMaterialsDto struct {
	Data []*CreateMMaterialDto `json:"data" binding:"required"`
}

type BulkUpdateMMaterialDto struct {
	IDs  []int64              `json:"ids" binding:"required"`
	Data *UpdateMMaterialDto `json:"data" binding:"required"`
}

type BulkDeleteMMaterialDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}

// MMaterialResponseDto represents a detailed view of MMaterial with related data.
type MMaterialResponseDto struct {
	models.MMaterials
}

type MMaterialFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
