// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

// CreateMSubLesson is used when creating a new MSubLesson.
type CreateMSubLessonDto struct {
	LessonID int64 `json:"lesson_id" binding:"required"`
    Title string `json:"title"`
	OrderPosition int `json:"order_position"`
}

// UpdateMSubLesson is used when updating an existing MSubLesson.
type UpdateMSubLessonDto struct {
	LessonID *int64 `json:"lesson_id"`
    Title *string `json:"title"`
	OrderPosition *int `json:"order_position"`
	IsActive *bool `json:"is_active"`
}

type BulkCreateMSubLessonsDto struct {
	Data []*CreateMSubLessonDto `json:"data" binding:"required"`
}

type BulkUpdateMSubLessonDto struct {
	IDs  []int64              `json:"ids" binding:"required"`
	Data *UpdateMSubLessonDto `json:"data" binding:"required"`
}

type BulkDeleteMSubLessonDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}

// MSubLessonResponseDto represents a detailed view of MSubLesson with related data.
type MSubLessonResponseDto struct {
	models.MSubLesson
}

type MSubLessonFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
