// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

type TCodeAnswerCreateDto struct {
	UserID         int64  `json:"user_id" validate:"required"`
	CodeQuestionID int64  `json:"code_question_id" validate:"required"`
	IsCodeRight    bool   `json:"is_code_right" validate:"required"`
	ExploringScore int    `json:"exploring_score" validate:"required"`
}

// TCodeAnswerResponseDto represents a detailed view of TCodeAnswer with related data.
type TCodeAnswerResponseDto struct {
	models.TCodeAnswer
}

type TCodeAnswerFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
