// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

type TCodeQuestionCreateDto struct {
	SubLessonID  int64  `json:"sub_lesson_id" validate:"required"`
	CodeQuestion string `json:"code_question" validate:"required"`
	Image        string `json:"image"`
	Score        int    `json:"score" validate:"required"`
	Hint         string `json:"hint"`
}

// TCodeQuestionResponseDto represents a detailed view of TCodeQuestion with related data.
type TCodeQuestionResponseDto struct {
	models.CodeQuestion
}

type TCodeQuestionFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
