// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

type TEssayAnswerCreateDto struct {
	EssayQuestionID int64  `json:"essay_question_id" validate:"required"`
	Answer         string `json:"answer" validate:"required"`
	KonteksPenjelasan int `json:"konteks_penjelasan" validate:"required"`
	Keruntutan      int    `json:"keruntutan" validate:"required"`
	Kebenaran       int    `json:"kebenaran" validate:"required"`
	TeacherNotes    string `json:"teacher_notes"`
	IsApprovedByTeacher bool   `json:"is_approved_by_teacher"`
}

// TEssayAnswerResponseDto represents a detailed view of TEssayAnswer with related data.
type TEssayAnswerResponseDto struct {
	models.TEssayAnswer
}

type TEssayAnswerFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
