// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)


// TStudentCourseResponseDto represents a detailed view of TStudentCourse with related data.
type TStudentCourseResponseDto struct {
	models.TStudentCourse
}

type TStudentCourseFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
