// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

// CompleteTStudentProgressDto is used when completing a student's progress.
type CompleteTStudentProgressDto struct {
	UserID   int64 `json:"user_id" validate:"required"`
	SubLessonID int64 `json:"sub_lesson_id" validate:"required"`
	Status   string `json:"status" validate:"required"`
}


// TStudentProgressResponseDto represents a detailed view of TStudentProgress with related data.
type TStudentProgressResponseDto struct {
	models.TStudentProgress
}

type TStudentProgressFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
