// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
)

type TWonderingScoreCreateDto struct {
	SubLessonID int64 `json:"sub_lesson_id" validate:"required"`
	Score       int   `json:"score" validate:"required"`
}

// TWonderingScoreResponseDto represents a detailed view of TWonderingScore with related data.
type TWonderingScoreResponseDto struct {
	models.TWonderingScore
}

type TWonderingScoreFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
