// title_dto.go - generated by api:generate title

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

// CreateTitleDto is used when creating a new Title.
type CreateTitleDto struct {
	Name       string `json:"name"`
	Code       string `json:"code"`
	Color      string `json:"color"`
	PositionID *int64 `json:"position_id"`
	LevelID    *int64 `json:"level_id"`
}

// UpdateTitleDto is used when updating an existing Title.
type UpdateTitleDto struct {
	Name       *string    `json:"name"`
	Code       *string    `json:"code"`
	Color      *string    `json:"color"`
	PositionID *int64     `json:"position_id"`
	LevelID    *int64     `json:"level_id"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type BulkCreateTitleDto struct {
	Data []*CreateTitleDto `json:"data" binding:"required"`
}

type BulkUpdateTitleDto struct {
	IDs  []int64         `json:"ids" binding:"required"`
	Data *UpdateTitleDto `json:"data" binding:"required"`
}

type BulkDeleteTitleDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}

// TitleResponseDto represents a detailed view of Title with related data.
type TitleResponseDto struct {
	models.Title
}

type TitleFilterDto struct {
	Preload     bool
	Sort        string
	Order       string
	Limit       int64
	Cursor      int64
	Name        string
	ShowDeleted bool
	Restore     bool
}
