// user_dto.go - generated by api:generate user

package dto

import (
	"jk-api/internal/database/models"
	"time"
)

// CreateUserDto is used when creating a new User.
type CreateUserDto struct {
	Code              *string `json:"code"`
	Name              string  `json:"name"`
	Email             string  `json:"email"`
	Password          string  `json:"password"`
	TitleID           *int64  `json:"title_id"`
	IsPasswordDefault *bool   `json:"is_password_default"`
}

// UpdateUserDto is used when updating an existing User.
type UpdateUserDto struct {
	Code              *string    `json:"code"`
	Name              *string    `json:"name"`
	Email             *string    `json:"email"`
	Password          *string    `json:"password"`
	OldPawword        *string    `json:"old_password"`
	NewPassword       *string    `json:"new_password"`
	TitleID           *int64     `json:"title_id"`
	RoleIDs           *[]int64   `json:"has_roles"`
	IsPasswordDefault *bool      `json:"is_password_default"`
	DeletedAt         *time.Time `json:"deleted_at"`
}

// UserResponseDto represents a detailed view of User with related data.
type UserResponseDto struct {
	models.User
}

type BulkCreateUserDto struct {
	Data []CreateUserDto `json:"users" binding:"required"`
}

type UserFilterDto struct {
	SquadID     int64
	Preload     bool
	Limit       int64
	Cursor      int64
	Name        string
	Sort        string
	Order       string
	ShowDeleted bool
	Restore     bool
}

type BulkUpdateUserDto struct {
	IDs      []int64        `json:"ids" binding:"required"`
	Data     *UpdateUserDto `json:"data"`
	HasRoles *[]int64       `json:"has_roles"`
}

type BulkDeleteUserDto struct {
	IDs []int64 `json:"ids" binding:"required"`
}
